"""empty message

Revision ID: edfae5124791
Revises: 8444e6de0b7f
Create Date: 2025-12-23 12:39:30.066202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edfae5124791'
down_revision = '8444e6de0b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
