
FROM python:3.12
# Устанавливаем рабочую директорию для проекта в контейнере

WORKDIR /coursApp
COPY . /coursApp
RUN pip install --upgrade pip -r requirements.txt
RUN python -m flask db upgrade

# Устанавливаем порт, который будет использоваться для сервера
EXPOSE 5000
