
FROM python:3.12
# Устанавливаем рабочую директорию для проекта в контейнере
RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
ENV DOCKER_ENV=true
WORKDIR /coursApp
COPY . /coursApp
RUN pip install --upgrade pip -r requirements.txt
COPY entrypoint.sh /entrypoint.sh


# Устанавливаем порт, который будет использоваться для сервера
EXPOSE 5000
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "main.py"]