
FROM python:3.12
# Устанавливаем рабочую директорию для проекта в контейнере
WORKDIR /Laba1

COPY requirements.txt /Laba1
RUN pip install --upgrade pip -r requirements.txt

COPY . /Laba1
# Устанавливаем порт, который будет использоваться для сервера
EXPOSE 5000
